### PR TITLE
Cash in close validation

### PR DESCRIPTION
**Pull request by aptasinskij**

### CODE REVIEW

**Comment by AndriiDronDiachuk** [comment]
@aptasinskij 
Method openCashInChannel (CashChannelsManager contract) allows make 2 and more requests to open channels.
Method must check whether at least one channel has status = 0 in this session, and restrict to be called ones again (restrict to send second request to open channel).

**Comment by AndriiDronDiachuk** [comment]
@aptasinskij 
Method confirmClose (CashChannelsManager contract) allows close channel even if it's in "open-request-status" (1).
Method must check whether channel status is "close-request" (3) before close channel.

**Comment by AndriiDronDiachuk** [comment]
@aptasinskij 
Methods of CashChannelsManager contract:
1) openCashInChannel,
2) confirmOpen,
3) closeCashInChannel,
4) confirmClose
are allowed to be called more than one time now.
These methods must restrict to be called more then one time.

**Comment by aptasinskij** [comment]
@AndriiDronDiachuk done. Waiting for your feedback

**Pull request merged**
